services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:80
    depends_on:
      auth-service:
        condition: service_started
      notes-fe-service:
        condition: service_started
  database:
    image: postgres:17.5
    hostname: notes-database
    env_file:
      - ./config/database.env
    volumes:
      - notes-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  auth-service:
    build: ./AuthService
    hostname: auth-service
    volumes:
      - ./config/AuthServiceSettings.json:/app/appsettings.json:ro
  notes-service:
    build: ./NotesService
    hostname: notes-service
    volumes:
      - ./config/NotesServiceSettings.json:/app/appsettings.json:ro
      - dpkeys-notes:/app/keys
    depends_on:
      database:
        condition: service_started
  notes-fe-service:
    build: ./NotesFEService
    hostname: notes-fe-service
    volumes:
      - ./config/NotesFEServiceSettings.json:/app/appsettings.json:ro
  user-service:
    build: ./UserService
    hostname: user-service
    volumes:
      - ./config/UserServiceSettings.json:/app/appsettings.json:ro
    depends_on:
      database:
        condition: service_started

volumes:
  notes-data:
  dpkeys-notes:
